# NUMPY / PANDAS ASSIGNMENT

## Q1. Replace all odd numbers in arr with -1 without changing arr

In [1]:
import numpy as np

original_array = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print("Original Array: ", original_array)

# replacing odd values with -1
changed_array = np.where(original_array % 2 == 1, -1, original_array)

print("\nArray after replacing odd values with -1 : ", changed_array)
print("\nOriginal Array: ", original_array)

Original Array:  [[0 1 2 3 4 5 6 7 8 9]]

Array after replacing odd values with -1 :  [[ 0 -1  2 -1  4 -1  6 -1  8 -1]]

Original Array:  [[0 1 2 3 4 5 6 7 8 9]]


## Q2. Get the common items between two python numpy arrays

In [2]:
Input1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
Input2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# retrieves common elements in Input1 and Input2.
commonItems = np.intersect1d(Input1, Input2)
commonItems

array([2, 4])

## Q3. From array a remove all items present in array b

In [3]:
num1 = np.array([1, 2, 3, 4, 5])
num2 = np.array([5, 6, 7, 8, 9])

# removing elements of num2 in num1.
diff_num1 = np.setdiff1d(num1, num2)

diff_num1

array([1, 2, 3, 4])

## Q4. Swap rows 1 and 2 in the array arr.

In [4]:
arr = np.arange(9).reshape(3, 3)
print("Original Array: \n",arr)

print("\nAfter Swapping Row 1 and Row 2 in arr: ")

swapped_rows_arr = arr[[0, 2, 1], :]
swapped_rows_arr

Original Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

After Swapping Row 1 and Row 2 in arr: 


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

## Q5. Swap columns 1 and 2 in the array arr.

In [5]:
arr = np.arange(9).reshape(3, 3)
print("Original Array: \n",arr)

print("\nAfter Swapping Column 1 and Column 2 in arr: ")

swapped_arr = arr[:, [0, 2, 1]]
swapped_arr

Original Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

After Swapping Column 1 and Column 2 in arr: 


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

## Q6.
###         a. Import the iris dataset keeping the text intact.
###         b. Extract the text column “species” from the 1D iris imported in previous question.

In [6]:
#dataset keeping the text intact
iris = np.genfromtxt("iris.data", delimiter=',', dtype='object')
print(iris[:5])

#Extracting 'species' column from dataset.
species = np.array([row[4] for row in iris])
print("\nSpecies Column:\n",species[:5])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]

Species Column:
 [b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


## Q7. Import the csv data from here, you will see some missing data.

### a. Find out what percent of the sf_permit dataset is missing

### b. Look at the columns Street Number Suffix and Zipcode from the sf_permits datasets. Both of these contain missing values. Which, if either, of these are missing because they don't exist? Which, if either, are missing because they weren't recorded?

### c. Try removing all the rows from the sf_permits dataset that contain missing values. How many are left?

### d. Now try removing all the columns with empty values. Now how much of your data is left?

### e. Try replacing all the NaN's in the sf_permit data with the one that comes directly after it and then [replace all the remaining na's with 0]


In [7]:
import pandas as pd
# Reading Building_Permits.csv file
sfPermits = pd.read_csv("Building_Permits.csv", dtype='object')

In [8]:
# 7.a Part

# total number of cells in dataframe
totalCells = np.product(sfPermits.shape)

# total number of missing values per column
missingCount = sfPermits.isnull().sum()

# total number of missing values in dataframe
totalMissing = missingCount.sum()

# percentage of missing values
percentage = round(((totalMissing/totalCells) * 100), 2)
print("The SF Permit dataset contains", percentage, "%", "missing values.")

The SF Permit dataset contains 26.26 % missing values.


In [9]:
# 7.b Part

print("Values Missing: ")
print(missingCount[['Street Number Suffix', 'Zipcode']])

StreetNoMissingPercentage = (round(((missingCount['Street Number Suffix'] / sfPermits.shape[0]) * 100), 2))
ZipcodeMissingPercentage = (round(((missingCount['Zipcode'] / sfPermits.shape[0]) * 100), 2))

print("\nPercent missing data in Street Number Suffix column =", StreetNoMissingPercentage)
print("Percent missing data in Zipcode column =", ZipcodeMissingPercentage)

print("\nThe missing values in Zipcode were not recorded as every address has zipcode.")
print("The values in Street Number Suffix are missing as they don't exist.")

Values Missing: 
Street Number Suffix    196684
Zipcode                   1716
dtype: int64

Percent missing data in Street Number Suffix column = 98.89
Percent missing data in Zipcode column = 0.86

The missing values in Zipcode were not recorded as every address has zipcode.
The values in Street Number Suffix are missing as they don't exist.


In [10]:
# 7.c Part

print("Total Rows in Original Dataset:", sfPermits.shape[0])

sfPermitsCleanedRows = sfPermits.dropna(axis=0)
print("Total Rows after NA's Dropped:", sfPermitsCleanedRows.shape[0])

Total Rows in Original Dataset: 198900
Total Rows after NA's Dropped: 0


In [11]:
# 7.d Part

print("Total Columns in Original Dataset:", sfPermits.shape[1])
sfPermitsCleanedColumns = sfPermits.dropna(axis=1)
print("Total Columns after NA's Dropped:", sfPermitsCleanedColumns.shape[1])

Total Columns in Original Dataset: 43
Total Columns after NA's Dropped: 12


In [12]:
# 7.e Part

# replacing all the NaN's in the sf_permit data with the one that comes directly after it 
# and then replacing all the remaining na's with 0.

sfPermitsCleaned = sfPermits.fillna(method='ffill', axis=0).fillna("0")
sfPermitsCleaned

Permit Number Permit Type            Permit Type Definition  \
0       201505065519           4                      sign - erect   
1       201604195146           4                      sign - erect   
2       201605278609           3  additions alterations or repairs   
3       201611072166           8            otc alterations permit   
4       201611283529           6                       demolitions   
...              ...         ...                               ...   
198895       M862628           8            otc alterations permit   
198896  201712055595           8            otc alterations permit   
198897       M863507           8            otc alterations permit   
198898       M863747           8            otc alterations permit   
198899       M864287           8            otc alterations permit   

       Permit Creation Date Block   Lot Street Number Street Number Suffix  \
0                05/06/2015  0326   023           140                    0   
1                04/19/2016  0306   007           440                    0   
2                05/27/2016  0595   203          1647                    0   
3                11/07/2016  0156   011          1230                    0   
4                11/28/2016  0342   001           950                    0   
...                     ...   ...   ...           ...                  ...   
198895           12/05/2017  0113  017A          1228                    A   
198896           12/05/2017  0271   014           580                    A   
198897           12/06/2017  4318   019          1568                    A   
198898           12/06/2017  0298   029           795                    A   
198899           12/07/2017  0160   006           838                    A   

       Street Name Street Suffix  ... Existing Construction Type  \
0            Ellis            St  ...                          3   
1            Geary            St  ...                          3   
2          Pacific            Av  ...                          1   
3          Pacific            Av  ...                          5   
4           Market            St  ...                          3   
...            ...           ...  ...                        ...   
198895  Montgomery            St  ...                          5   
198896        Bush            St  ...                          5   
198897     Indiana            St  ...                          5   
198898      Sutter            St  ...                          5   
198899     Pacific            Av  ...                          5   

       Existing Construction Type Description Proposed Construction Type  \
0                               constr type 3                          0   
1                               constr type 3                          0   
2                               constr type 1                          1   
3                              wood frame (5)                          5   
4                               constr type 3                          5   
...                                       ...                        ...   
198895                         wood frame (5)                          5   
198896                         wood frame (5)                          5   
198897                         wood frame (5)                          5   
198898                         wood frame (5)                          5   
198899                         wood frame (5)                          5   

       Proposed Construction Type Description Site Permit Supervisor District  \
0                                           0           0                   3   
1                                           0           0                   3   
2                               constr type 1           0                   3   
3                              wood frame (5)           0                   3   
4                              wood frame (5)           0                   6   
...          